Remove ogg and item_drop improve

diff --git a/build/android/Makefile b/build/android/Makefile
--- a/build/android/Makefile
+++ b/build/android/Makefile
@@ -64,17 +64,16 @@ ASSETS_TIMESTAMP = deps/assets_timestamp
 
 OPENAL_FOLDER = $(ROOT)/deps/openal-soft
 OPENAL_DIR = $(ROOT)/deps/openal-soft/android
-OPENAL_LIB = $(OPENAL_DIR)libs/$(TARGET_ABI)/libopenal.so
+OPENAL_LIB = $(OPENAL_DIR)/libs/$(TARGET_ABI)/libopenal.so
 OPENAL_TIMESTAMP = $(OPENAL_DIR)/timestamp
 OPENAL_TIMESTAMP_INT = $(ROOT)/deps/openal_timestamp
 OPENAL_URL_GIT = https://github.com/MoNTE48/openal-soft
 
-OGG_DIR = $(ROOT)/deps/libvorbis-libogg-android
-OGG_LIB = $(OGG_DIR)/libs/$(TARGET_ABI)/libogg.so
-VORBIS_LIB = $(OGG_DIR)/libs/$(TARGET_ABI)/libogg.so
-OGG_TIMESTAMP = $(OGG_DIR)/timestamp
-OGG_TIMESTAMP_INT = $(ROOT)/deps/ogg_timestamp
-OGG_URL_GIT = https://github.com/MoNTE48/libvorbis-libogg-android
+VORBIS_DIR = $(ROOT)/deps/libvorbis-android
+VORBIS_LIB = $(VORBIS_DIR)/libs/$(TARGET_ABI)/libvorbis.so
+VORBIS_TIMESTAMP = $(VORBIS_DIR)/timestamp
+VORBIS_TIMESTAMP_INT = $(ROOT)/deps/vorbis_timestamp
+VORBIS_URL_GIT = https://github.com/MoNTE48/libvorbis-android
 
 IRRLICHT_COMMIT = 58fa0cf3419c2733159fc3c6253634bedada3bfe
 #IRRLICHT_COMMIT = 54b8cba398c3b845d0d1158822916c2f78be194b
@@ -119,8 +118,8 @@ ICONV_TIMESTAMP = $(ICONV_DIR)/timestamp
 ICONV_TIMESTAMP_INT = $(ROOT)/deps/iconv_timestamp
 ICONV_URL_HTTP = http://ftp.gnu.org/pub/gnu/libiconv/libiconv-$(ICONV_VERSION).tar.gz
 
-SQLITE3_VERSION= 3110100
-SQLITE3_DIR = $(ROOT)/deps/sqlite-amalgamation-$(SQLITE3_VERSION)
+SQLITE3_VERSION= 3120000
+SQLITE3_DIR = $(ROOT)/deps/sqlite
 SQLITE3_URL = http://www.sqlite.org/2016/sqlite-amalgamation-$(SQLITE3_VERSION).zip
 
 LUAJIT_GIT_BRANCH = v2.1
@@ -155,7 +154,7 @@ VERSION_PATCH := $(shell cat $(ROOT)/../../CMakeLists.txt | \
 	install_debug install envpaths all \
 	manifest clean_manifest\
 	$(ASSETS_TIMESTAMP) $(LUAJIT_TIMESTAMP) \
-	$(OPENAL_TIMESTAMP) $(OGG_TIMESTAMP) \
+	$(OPENAL_TIMESTAMP) $(VORBIS_TIMESTAMP) \
 	$(IRRLICHT_TIMESTAMP) $(CURL_TIMESTAMP) \
 	$(OPENSSL_TIMESTAMP) $(VORBIS_TIMESTAMP) \
 	$(ROOT)/jni/src/android_version.h \
@@ -240,48 +239,48 @@ $(OPENAL_LIB): $(OPENAL_TIMESTAMP)
 clean_openal :
 	$(RM) -rf ${OPENAL_FOLDER}
 
-$(OGG_TIMESTAMP) : ogg_download
-	@LAST_MODIF=$$(find ${OGG_DIR} -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" "); \
+$(VORBIS_TIMESTAMP) : vorbis_download
+	@LAST_MODIF=$$(find ${VORBIS_DIR} -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" "); \
 	if [ $$(basename $$LAST_MODIF) != "timestamp" ] ; then                     \
-		touch ${OGG_TIMESTAMP};                                                \
+		touch ${VORBIS_TIMESTAMP};                                                \
 	fi
 
-ogg_download :
-	@if [ ! -d ${OGG_DIR} ] ; then                                             \
-		echo "ogg sources missing, downloading...";                            \
+vorbis_download :
+	@if [ ! -d ${VORBIS_DIR} ] ; then                                             \
+		echo "vorbis sources missing, downloading...";                            \
 		mkdir -p ${ROOT}/deps;                                                 \
 		cd ${ROOT}/deps ;                                                      \
-		git clone ${OGG_URL_GIT}|| exit 1;                                     \
+		git clone ${VORBIS_URL_GIT}|| exit 1;                                     \
 	fi
 
-ogg : $(OGG_LIB)
+vorbis : $(VORBIS_LIB)
 
-$(OGG_LIB): $(OGG_TIMESTAMP)
+$(VORBIS_LIB): $(VORBIS_TIMESTAMP)
 	+ @REFRESH=0;                                                                \
-	if [ ! -e ${OGG_TIMESTAMP_INT} ] ; then                                    \
-		echo "${OGG_TIMESTAMP_INT} doesn't exist";                             \
+	if [ ! -e ${VORBIS_TIMESTAMP_INT} ] ; then                                    \
+		echo "${VORBIS_TIMESTAMP_INT} doesn't exist";                             \
 		REFRESH=1;                                                             \
 	fi;                                                                        \
-	if [ ${OGG_TIMESTAMP} -nt ${OGG_TIMESTAMP_INT} ] ; then                    \
+	if [ ${VORBIS_TIMESTAMP} -nt ${VORBIS_TIMESTAMP_INT} ] ; then                    \
 		REFRESH=1;                                                             \
 	fi;                                                                        \
 	if [ $$REFRESH -ne 0 ] ; then                                              \
 	export PATH=$$PATH:${ANDROID_NDK};                                         \
-	echo "changed timestamp for ogg detected building...";                     \
-	cd ${OGG_DIR};                                                             \
+	echo "changed timestamp for vorbis detected building...";                     \
+	cd ${VORBIS_DIR};                                                             \
 	ndk-build NDEBUG=${NDEBUG}                                                 \
 	APP_ABI=${TARGET_ABI} APP_PLATFORM=${APP_PLATFORM}                         \
 	TARGET_CFLAGS+="${TARGET_CFLAGS_ADDON}"                                    \
 	TARGET_LDFLAGS+="${TARGET_LDFLAGS_ADDON}"                                  \
 	TARGET_CXXFLAGS+="${TARGET_CXXFLAGS_ADDON}" || exit 1;                     \
-	touch ${OGG_TIMESTAMP};                                                    \
-	touch ${OGG_TIMESTAMP_INT};                                                \
+	touch ${VORBIS_TIMESTAMP};                                                    \
+	touch ${VORBIS_TIMESTAMP_INT};                                                \
 	else                                                                       \
-		echo "nothing to be done for libogg/libvorbis";                        \
+		echo "nothing to be done for libvorbis/libvorbis";                        \
 	fi
 
-clean_ogg :
-	$(RM) -rf ${OGG_DIR}
+clean_vorbis :
+	$(RM) -rf ${VORBIS_DIR}
 
 $(OPENSSL_TIMESTAMP) : openssl_download
 	@LAST_MODIF=$$(find ${OPENSSL_DIR} -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" "); \
@@ -348,7 +347,7 @@ freetype_download :
 		wget ${FREETYPE_URL_HTTP} || exit 1;                                    \
 		tar -xjf freetype-${FREETYPE_VERSION}.tar.bz2 || exit 1;                \
 		rm freetype-${FREETYPE_VERSION}.tar.bz2;                                \
-		mv freetype-${FREETYPE_VERSION} freetype;                            \
+		mv freetype-${FREETYPE_VERSION} freetype;                               \
 	fi
 
 freetype : $(FREETYPE_LIB)
@@ -626,19 +625,19 @@ $(GMP_LIB): $(GMP_TIMESTAMP)
 clean_gmp:
 	$(RM) -R deps/gmp
 
-sqlite3_download:
-	@if [ ! -d ${SQLITE3_DIR} ] ; then                                           \
-	echo "SQLITE sources missing, downloading...";                               \
-	mkdir -p ${ROOT}/deps;                                                       \
-	cd ${ROOT}/deps;                                                             \
-	wget ${SQLITE3_URL};                                                         \
-	unzip sqlite-amalgamation-$(SQLITE3_VERSION).zip;                            \
-	rm sqlite-amalgamation-$(SQLITE3_VERSION).zip;                               \
-	ln -s ${SQLITE3_DIR} sqlite;                                                 \
-	fi
+sqlite3_download: deps/${SQLITE3_FOLDER}/sqlite3.c
+
+deps/${SQLITE3_FOLDER}/sqlite3.c :
+	mkdir -p ${ROOT}/deps;                                                     \
+	cd ${ROOT}/deps;                                                           \
+	rm -R sqlite;                                                              \
+	wget ${SQLITE3_URL};                                                       \
+	unzip sqlite-amalgamation-$(SQLITE3_VERSION).zip || exit 1;                \
+	rm sqlite-amalgamation-$(SQLITE3_VERSION).zip;                             \
+	mv sqlite-amalgamation-$(SQLITE3_VERSION) sqlite;                          \
+fi
 
 clean_sqlite3:
-	cd deps && $(RM) -rf ${SQLITE3_DIR} && \
 	$(RM) -R sqlite
 
 $(ASSETS_TIMESTAMP) : $(IRRLICHT_LIB)
@@ -756,7 +755,7 @@ clean_assets :
 
 apk: $(PATHCFGFILE) assets $(ICONV_LIB) $(IRRLICHT_LIB) $(CURL_LIB) $(GMP_LIB) \
     $(LUAJIT_LIB)                                                              \
-	$(OPENAL_LIB) $(OGG_LIB) prep_srcdir $(ROOT)/jni/src/android_version.h     \
+	$(OPENAL_LIB) $(VORBIS_LIB) prep_srcdir $(ROOT)/jni/src/android_version.h     \
 	$(ROOT)/jni/src/android_version_githash.h sqlite3_download
 	@export NDEBUG=$$NDEBUG; $(MAKE) manifest;                                 \
 	export PATH=$$PATH:${SDKFOLDER}/platform-tools:${ANDROID_NDK};             \
